#FIXME this is a hack to make sure that my http Connector in SecureTomcatConfiguration
# doesn't crash app with address already in use if I left port at 8080
server:
  port: 8181

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

security:
  user:
    name: admin
    password: bootdemo
